#!/usr/bin/env zsh

CACHE=$HOME/.cache/rofi-keepassxc/
mkdir -p $CACHE

DB="$HOME/Passwords/keepass.kdbx"
DBPASS=$(rofi -dmenu -i -p "Enter your database password" -l 0 -password)

choose_action() {
	if [ -n "$ENTRY" ]; then
		ACTION="$(printf "Clip username\nClip password\nDelete" | rofi -dmenu -i -p "Choose action for \"$ENTRY\" entry" -l 3)"
	fi

	case "$ACTION" in
		"Clip username") echo $DBPASS | keepassxc-cli show $DB $ENTRY | grep 'UserName:' | cut -b 11- | xclip -selection clipboard;;
		"Clip password") echo $DBPASS | keepassxc-cli clip $DB $ENTRY;;
		Delete) echo $DBPASS | keepassxc-cli rm $DB $ENTRY;;	
	esac
}

ERROR_MSG='Error while reading the database'
CHECK=$(echo $DBPASS | keepassxc-cli open $DB &> $CACHE/tmp && grep -oh $ERROR_MSG $CACHE/tmp)

if [ "$CHECK" = "$ERROR_MSG" ]; then
	rofi -e "$ERROR_MSG"
else
	ELEMENTS_NUM=$(if [ "$($ENTRY | wc -l)" > 20 ]; then echo 20; fi)
	ENTRY=$(echo $DBPASS | keepassxc-cli ls $DB | grep -Ev 'Enter|?*/' | sort | rofi -dmenu -i -p "Entry list" -l $ELEMENTS_NUM)

	choose_action
fi

rm -r $CACHE/tmp
